[package]
name = "physics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_ecs = { workspace = true }
temper-components = { workspace = true }
bevy_math = { workspace = true }
temper-core = { workspace = true }
temper-state = { workspace = true }
temper-entities = { workspace = true }
temper-macros = { workspace = true }
temper-messages = { workspace = true }
temper-physics = { workspace = true }
tracing = { workspace = true }