[package]
name = "bin-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
temper-general-purpose = { workspace = true }