[package]
name = "ionic-entities"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_ecs = { workspace = true }
bevy_math = { workspace = true }

ionic-core = { workspace = true }
ionic-data = { workspace = true }
ionic-components = { workspace = true }
