[package]
name = "packets"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_ecs = { workspace = true }
temper-core = { workspace = true }
temper-components = { workspace = true }
temper-protocol = { workspace = true }
tracing = { workspace = true }
temper-messages = { workspace = true }
temper-text = { workspace = true }
temper-state = { workspace = true }
temper-inventories = { workspace = true }
temper-commands = { workspace = true }
temper-net-runtime = { workspace = true }
temper-codec = { workspace = true }
temper-config = { workspace = true }
once_cell = { workspace = true }
serde_json = { workspace = true }
temper-macros = { workspace = true }