[package]
name = "temper-app"
edition.workspace = true
version.workspace = true

[dependencies]
bin-cli = { path = "cli" }
bin-import = { path = "import" }
bin-runtime = { path = "runtime" }


[lints]
workspace = true
