[package]
name = "world-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
temper-world-format = { workspace = true }
noise = { workspace = true }
temper-core = { workspace = true }
temper-macros = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rand = { workspace = true }