[package]
name = "ionic"
description = "A high-performance Minecraft server implementation, crafted in Rust for unparalleled speed and efficiency."
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
ionic-dashboard = { workspace = true, optional = true }
dhat = { workspace = true, optional = true }
ionic-config = { workspace = true }
ionic-logging = { workspace = true }
tracy-client = { workspace = true, optional = true }
clap = { workspace = true }

ionic-app = { workspace = true }
tracing = { workspace = true }
ionic-registry = { workspace = true }

[features]
dhat = ["dep:dhat"]
dashboard = [
    "dep:ionic-dashboard",
    "ionic-config/dashboard"
]
default = [
    "dashboard"
]
tracy = ["ionic-logging/tracy", "dep:tracy-client"]

[dev-dependencies]
tempfile = { workspace = true }

[[bin]]
name = "ionic"
path = "src/main.rs"
