[package]
name = "temper"
description = "A high-performance Minecraft server implementation, crafted in Rust for unparalleled speed and efficiency."
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
temper-dashboard = { workspace = true, optional = true }
dhat = { workspace = true, optional = true }
temper-config = { workspace = true }
temper-logging = { workspace = true }
tracy-client = { workspace = true, optional = true }
clap = { workspace = true }

temper-app = { workspace = true }
tracing = { workspace = true }
temper-registry = { workspace = true }

[features]
dhat = ["dep:dhat"]
dashboard = [
    "dep:temper-dashboard",
    "temper-config/dashboard"
]
default = [
    "dashboard"
]
tracy = ["temper-logging/tracy", "dep:tracy-client"]

[dev-dependencies]
tempfile = { workspace = true }

[[bin]]
name = "temper"
path = "src/main.rs"
