[package]
name = "temper-state"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = { workspace = true }
temper-world = { workspace = true }
dashmap = { workspace = true }
temper-threadpool = { workspace = true }
crossbeam-queue = { workspace = true }
tempfile = { workspace = true }
