[package]
name = "temper-codec"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
bitcode = { workspace = true }
temper-general-purpose = { workspace = true }
deepsize = { workspace = true }

